# Generated by Django 5.2.16 on 2026-07-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='suggestions',
            field=models.JSONField(default=list),
        ),
    ]
